apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "spec-customer"
  description: "Artifacts generator via Spec."
  annotations:
    github.com/project-slug: veecode-homolog/spec-customer
    backstage.io/techdocs-ref: dir:..
    github.com/workflows: publish.yml,remove.yml
    kong-manager/service-name: app.spec-customer.80
    kong-manager/instance: demo-cluster-ec2
    kong-manager/spec : openapi-swagger.yaml
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
  providesApis:
    - spec-customer
